services:
  - type: web
    name: virtual-try-on
    runtime: static
    rootDir: virtualtryon
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
